name = "LeanSDK"
defaultTargets = ["lean-sdk"]

[[lean_lib]]
name = "LeanSDK"

[[lean_exe]]
name = "lean-sdk"
root = "LeanSDK.Main"
supportInterpreter = true

[[require]]
name = "REPL"
git = "https://github.com/leanprover-community/repl.git"
