name = "LeanSDK"
defaultTargets = ["lean-sdk"]

[[lean_lib]]
name = "LeanSDK"

[[lean_exe]]
name = "lean-sdk"
root = "LeanSDK.Main"
supportInterpreter = true

[[lean_exe]]
name = "repl"
root = "REPL.Main"
supportInterpreter = true
