from typing import Optional
from enum import Enum
from pydantic import BaseModel, Field


class LeanError(BaseModel):
    error: str = Field(
        description="The error message",
    )


class Pos(BaseModel):
    line: int = Field(
        description="The line of the message",
    )
    column: int = Field(
        description="The column of the message",
    )


class MessageSeverity(str, Enum):
    info = "info"
    warning = "warning"
    error = "error"


class Message(BaseModel):
    severity: MessageSeverity = Field(
        description="The severity of the message (info, warning, error, etc.)",
    )
    pos: Pos = Field(
        description="The (start) position of the message",
    )
    endPos: Optional[Pos] = Field(
        description="The end position of the message",
        default=None,
    )
    data: str = Field(
        description="The data of the message",
    )


class Sorry(BaseModel):
    pos: Optional[Pos] = Field(
        description="The (start) position of the sorry",
        default=None,
    )
    endPos: Optional[Pos] = Field(
        description="The end position of the sorry",
        default=None,
    )
    goal: str = Field(
        description="The goal of the sorry",
    )
    proofState: int = Field(
        description="The proof state number of the sorry",
    )


class CommandResponse(BaseModel):
    messages: list[Message] = Field(description="The list of messages", default=[])
    sorries: list[Sorry] = Field(description="The list of sorries", default=[])
    env: int = Field(
        description="The environment generated by the command",
    )


class TacticResponse(BaseModel):
    proofState: int = Field(
        description="The proof state number of the tactic",
    )
    goals: list[str] = Field(
        description="The list of goals",
    )
    proofStatus: Optional[str] = Field(
        description="The proof status after the tactic",
        default=None,
    )
    sorries: list[Sorry] = Field(
        description="The list of sorries produced by the tactic",
        default=[],
    )
